-- CREATE TABLE : payments
CREATE TABLE payments (
payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
loan_id INTEGER NOT NULL REFERENCES loans(loan_id),
payment_date DATE NOT NULL,
principal_paid NUMERIC(14,2) NOT NULL CHECK (principal_paid >= 0),
interest_paid NUMERIC(14,2) NOT NULL CHECK (interest_paid >= 0),
total_paid NUMERIC(14,2) NOT NULL CHECK (total_paid >= 0),
payment_status VARCHAR(20) NOT NULl DEFAULT 'PAID'
);
SELECT * FROM payments;

-- Insert data to column
INSERT INTO payments
(loan_id, payment_date, principal_paid, interest_paid, total_paid)
VALUES
(7, '2026-03-01', 5000.00, 500.00, 5500.00),
(7, '2026-04-01', 5000.00, 450.00, 5450.00),
(8, '2026-03-15', 3000.00, 300.00, 3300.00);
SELECT * FROM payments;

--แล้วลอง JOIN 3 ตาราง
SELECT
    m.member_no,
    m.full_name,
    l.loan_no,
    l.principal,
    p.payment_date,
    p.total_paid
FROM members m
JOIN loans l
ON m.member_id = l.member_id
JOIN payments p
ON l.loan_id = p.loan_id
ORDER BY m.member_no, p.payment_date;

SELECT *
FROM payments
WHERE loan_id = 7
ORDER BY payment_date;

-- Start Work
BEGIN; -- = เริ่ม “ชุดงาน”

INSERT INTO payments
(
	loan_id,
	payment_date,
	principal_paid,
	interest_paid,
	total_paid
)
VALUES
(
	7,
	'2026-05-01',
	5000.00,
	400.00,
	5400.00
);

UPDATE loans
SET principal = principal - 5000.00
WHERE loan_id = 7;

COMMIT; -- = ยืนยันให้ทั้ง 2 งานถูกบันทึกจริง
/*เพราะงั้น BEGIN ... COMMIT คือการบอก PostgreSQL ว่า:

“สองคำสั่งนี้เป็นธุรกรรมเดียวกัน ต้องสำเร็จไปด้วยกัน”*/

-- Check 
SELECT *
FROM loans
WHERE loan_id = 7;

SELECT *
FROM payments
WHERE loan_id = 7
ORDER BY payment_date;

-- Start Work
BEGIN; -- = เริ่ม “ชุดงาน”

INSERT INTO payments
(
	loan_id,
	payment_date,
	principal_paid,
	interest_paid,
	total_paid
)
VALUES
(
    7,
    '2026-06-01',
    4000.00,
    300.00,
    4300.00
);

UPDATE loans
SET principal = principal - 5000.00
WHERE loan_id = 7;

COMMIT;

SELECT * FROM loans;

-- 2) ฝึก SAVEPOINT
/*อันนี้เป็นระดับต่อจาก ROLLBACK
สมมติ Transaction มีหลายขั้น แล้วเราอยากย้อนกลับเฉพาะบางส่วน*/
BEGIN;

INSERT INTO payments
(
	loan_id,
	payment_date,
	principal_paid,
	interest_paid,
	total_paid
)
VALUES
(
	7,
	'2026-07-01',
	3000.00,
	250.00,
	3250.00
);

SAVEPOINT after_payment;

UPDATE loans
SET principal = principal - 3000
WHERE loan_id = 7;

-- สมมติรู้ว่าการ UPDATE ผิด
ROLLBACK TO SAVEPOINT after_payment;

COMMIT;


-- 4) หา Loan ที่ยังไม่มีการชำระ
SELECT 
	m.member_no,
	m.full_name,
	l.loan_no,
	l.principal
FROM members m
JOIN loans l
ON m.member_id = l.loan_id
LEFT JOIN payments p 
ON l.loan_id = p.loan_id
WHERE p.payment_id IS NULL;

-- 5) ฝึก INDEX
CREATE INDEX idx_payments_payment_date
ON payments(payment_date);
-- ดู index:
SELECT 
	indexname,
	indexdef
FROM pg_indexes
WHERE tablename = 'payments';
-- ถ้าจะลบ:
DROP INDEX idx_payments_payment_date;
/*Index ช่วยให้ค้นเร็วขึ้น แต่ทำให้ INSERT/UPDATE มีต้นทุนเพิ่มขึ้น*/

-- 6) ฝึก VIEW
/*อันนี้เริ่มเหมือนระบบองค์กรจริงมากขึ้น
สร้าง View สำหรับรายงาน Loan + Member:*/
CREATE VIEW vw_member_loans AS 
SELECT
	m.member_no,
	m.full_name,
	l.loan_no,
	l.loan_type,
	l.principal,
	l.annual_rate,
	l.status
FROM members m
JOIN loans l
ON m.member_id = l.member_id
-- ใช้งาน:
SELECT *
FROM vw_member_loans
/* ข้อดีคือเราไม่ต้องเขียน JOIN เดิมซ้ำทุกครั้ง
ถ้าจะลบ: */
DROP VIEW vw_member_loans;





