CREATE TABLE users
    (
        user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
        username      VARCHAR(30) NOT NULL UNIQUE                          ,
        password_hash TEXT NOT NULL                                        ,
        role          VARCHAR(20) NOT NULL DEFAULT 'USER'                  ,
        status        VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'                ,
        created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP        ,
        CONSTRAINT chk_user_role CHECK (role IN ('ADMIN', 'USER'))         ,
        CONSTRAINT chk_user_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
    );

SELECT * FROM users;