--[[ 01_create_members_table สร้างตาราง members, PK, UNIQUE, Default, Constraint ]]

-- Crate new table in project คำสั่งนี้ต้องย้ายไปไว้ที่โฟลเดอร์อื่นไหม
CREATE TABLE deposit_account (
account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
member_id INTEGER NOT NULL,
account_no VARCHAR(30) UNIQUE NOT NULL,
account_type VARCHAR(30) NOT NULL,
balance NUMERIC(14,2) NOT NULL DEFAULT 0,
opened_date DATE NOT NULL
)
-- Delte table and data in table
DROP TABLE /*Table name*/;
-- Delte only data in table
DELETE FROM /*Table name*/;
-- Fixt structure in table : Add new colum
ALTER TABLE members
ADD COLUMN phone VARCHAR(20);
-- Fix structure in table: Change Type / Length
ALTER TABLE members
ALTER COLUMN phone TYPE VARCHAR(30);
-- Fix structure in table: Delete Culumn
ALTER TABLE members
DROP COLUMN phone;
-- Meaning of Commands
/*
CREATE = สร้างใหม่
ALTER = แก้ของเดิม
DROP = ลบทิ้ง
*/

-- Insert data to table
INSERT INTO members
(member_no, full_name, department, join_date)
VALUES
('M004', 'Sarawut Kaikeaw', 'Software Engineer', '2025-05-10');

-- [[ UPDATE ]]
-- Update data in table
UPDATE members
SET department = 'GameDeveloper'
WHERE member_no = 'M001';

-- [[ DELETE ]]
-- Delete data in table
DELETE FROM members
WHERE member_id = '1';

-- [[ RED ]]
-- Read all data in table
SELECT * FROM members;
-- Read by select colum
SELECT member_no, full_name
FROM members;
-- Read sort by Status:Active
SELECT *
FROM members
ORDER BY status = 'ACTIVE';
-- Read sort by name
SELECT *
FROM members
ORDER BY full_name;
-- Read data sort name  A-Z
SELECT *
FROM members
ORDER BY full_name ASC;
-- Read data sort name  Z-A
SELECT *
FROM members
ORDER BY full_name DESC;
-- Read sort by member_id Start by low
SELECT * 
FROM members
ORDER BY member_id ASC;
-- Read sort by member_id Start by high
SELECT * 
FROM members
ORDER BY member_id DESC;
-- Read by input limit of data to read: LIMIT
SELECT *
FROM members
LIMIT 2;
-- Read data by word : LIKE ** Have focus small and big of letter
SELECT *
FROM members
WHERE full_name LIKE '%Su%';
-- Read data by word : ILIKE ** Not have to focus small and big letter
SELECT *
FROM members
WHERE full_name ILIKE '%S%';
-- Read select column
SELECT member_id, member_no, full_name
FROM members
ORDER BY member_id;

-- AND / OR
-- [[ AND ]]
SELECT *
FROM members
WHERE department = 'IT' -- Input department string
AND status = 'ACTIVE';
-- [[ OR ]]
SELECT *
FROM members
WHERE department = 'IT'
OR department = 'Software Engineer';
-- [[ IN — เขียนหลายค่าให้สวยกว่า OR ]]
SELECT *
FROM members
WHERE department IN ('IT', 'GameDeveloper', 'Software Engineer');

-- COUNT — นับจำนวน colum in table return by integer
SELECT COUNT(*)
FROM members;

-- นับเฉพาะ ACTIVE:
SELECT COUNT(*)
FROM members
WHERE status = 'ACTIVE'
-- Test cahnge status some user
UPDATE members
SET status = 'OffLine'
WHERE member_no = 'M001';
SELECT * FROM members;

-- GROUP BY — เริ่มเข้าสู่ Data Analysis
SELECT department, COUNT(*) AS total_members -- AS total_members คือการตั้งชื่อผลลัพธ์ให้อ่านง่าย
FROM members
GROUP BY department;
-- [ TEST ]
-- Delete all coulum
DELETE FROM deposit_account;
-- Delete Table
DROP TABLE deposit_account;
-- Read all
--SELECT * FROM deposit_account;

-- TEST Create new Table: deposit_accounts
CREATE TABLE deposit_accounts (
account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

member_id INTEGER NOT NULL
REFERENCES members(member_id), 
-- หมายความว่า member_id ใน deposit_accounts ต้องมีอยู่จริงในตาราง members

account_no VARCHAR(30) UNIQUE NOT NULL,
account_type VARCHAR(30) NOT NULL,
balance NUMERIC(14,2) NOT NULL DEFAULT 0,
opened_date DATE NOT NULL
)

-- TEST add value to table
INSERT INTO deposit_accounts
(account_id, account_no, account_type, balance, opened_date)
VALUES
('2', 'D001', 'BANK', '450', '2019-01-01'); -- HOW TO CREATE
SELECT * FROM deposit_accounts;


