-- 01 ดูสมาชิกทั้งหมด
SELECT * FROM members;

INSERT INTO members
(member_no, full_name, department, join_date)
VALUES
('M006', 'Aekkalak Keawwandee', 'Master Host', '2015-08-09')
SELECT * FROM members;

-- 02 เรียงชื่อตามตัวอักษร
SELECT *
FROM members
ORDER BY full_name;

-- 03 หาเฉพาะ ACTIVE
SELECT * 
FROM members
WHERE status = 'ACTIVE';

-- 04 ค้นชื่อที่มีคำว่า chai
SELECT *
FROM members
WHERE full_name ILIKE ('%c%');

-- 05 นับสมาชิกทั้งหมด
SELECT COUNT(*) AS All_Members
FROM members;

-- 06 นับสมาชิกแยกตาม department
SELECT department, COUNT(*) AS Department_Count
FROM members
GROUP BY department;

-- Delete table all
DROP TABLE deposit_accounts;
-- แล้วสร้าง Table ใหม่ด้วยตัวเอง:
CREATE TABLE deposit_accounts (
account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
member_id INTEGER NOT NULL REFERENCES members(member_id),
account_no INTEGER UNIQUE NOT NULL,
account_type VARCHAR(30) NOT NULL,
balance NUMERIC(14,2) NOT NULL DEFAULT 0,
opened_date DATE NOT NULL
);
SELECT * FROM deposit_accounts;


