-- CREATE TABLE : leoan
CREATE TABLE loans (
loan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
member_id INTEGER NOT NULL REFERENCES members(member_id),
loan_no VARCHAR(30) UNIQUE NOT NULL,
loan_type VARCHAR(30) NOT NULL,
principal NUMERIC(14,2) NOT NULL,
annual_rate NUMERIC(5,2) NOT NULL,
start_date DATE NOT NULL,
status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

-- Add data clumn to table
INSERT INTO loans
(member_id, loan_no, loan_type, principal, annual_rate, start_date)
VALUES
(2, 'L001', 'ORDINARY', 100000.00, 5.50, '2025-05-18'),
(3, 'L002', 'EMERGENCY', 50000.00, 6.00, '2024-12-15');

-- SHOW data in table
SELECT * FROM loans

-- ถ้าคุณอยากดูว่า Sequence ของแต่ละ ID ตอนนี้อยู่ตรงไหน ลอง:
SELECT pg_get_serial_sequence('loans', 'loan_id');
