-- Create table : audit_logs
CREATE TABLE audit_logs (
	audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- = ID ของ log
	
	table_name VARCHAR(50) NOT NULL, -- = ตารางที่ถูกแก้ เช่น loans
	record_id INTEGER NOT NULL, -- = ID ของ record ที่ถูกแก้
	
	action_type VARCHAR NOT NULL, -- = UPDATE / INSERT / DELETE

	old_data JSONB, -- = ข้อมูลก่อนแก้
	new_data JSONB, -- = ข้อมูลหลังแก้
	/*เอาไว้เก็บข้อมูลทั้ง Row ในรูป JSON
	{
	  "loan_id": 7,
	  "principal": 150000,
	  "status": "ACTIVE"
	}
	*/

	Changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- เวลาแก้
)

-- 3. สร้าง Trigger Function
-- PostgreSQL Trigger ต้องมี Function ก่อน
CREATE OR REPLACE FUNCTION audit_loans_changes()
RETURNS TRIGGER
AS $$
BEGIN

	INSERT INTO audit_logs
    (
        table_name,
        record_id,
        action_type,
        old_data,
        new_data
    )
	VALUES
	(
		'loans',
		NEW.loan_id,
		'UPDATE',
		to_jsonb(OLD),
		to_jsonb(NEW)
	);

	RETURN NEW;

END;
$$ LANGUAGE plpgsql;
/*
ตรงนี้มีคำใหม่:
OLD = ข้อมูลก่อน UPDATE
NEW = ข้อมูลหลัง UPDATE

สมมติเดิม:
principal = 150000

แล้วรัน:
UPDATE loans
SET principal = 145000
WHERE loan_id = 7;

Trigger จะเห็น:
OLD.principal = 150000
NEW.principal = 145000

*/

-- 4. สร้าง Trigger
CREATE TRIGGER trg_audit_loans_update -- ตั้งชื่อ Trigger
AFTER UPDATE
ON loans -- ไปวาง Event ไว้ที่ตารางไหน
FOR EACH ROW
EXECUTE FUNCTION audit_loans_changes(); -- เรียกชื่อฟังก์ชั่นที่เชื่อมกับ Trigger
/*
จำโครง:
CREATE TRIGGER ชื่อ
AFTER UPDATE
ON ตาราง
FOR EACH ROW
EXECUTE FUNCTION function_name();
*/

-- 5. ทดลองใช้งาน
-- ดูก่อน:
SELECT *
FROM loans
WHERE loan_id = 7;

-- แล้วลองแก้:
UPDATE loans
SET annual_rate = 7.50
WHERE loan_id = 7;

-- จากนั้น:
SELECT *
FROM audit_logs
ORDER BY audit_id DESC;

-- View all in audit_logs
SELECT * FROM audit_logs;

-- 6. ลองอ่าน JSONB
SELECT
	audit_id,
	
	old_data ->> 'annual_rate' AS old_rate,
	new_data ->> 'annual_rate' AS new_rate,
	/*คือดึงค่า annual_rate จาก JSON*/
	
	changed_at
FROM audit_logs
ORDER BY audit_id DESC;
/*จำ:
->   ได้ JSON
->>  ได้ Text*/


/*7. ทำ Trigger สำหรับ INSERT / DELETE เพิ่ม
ยังไม่ต้องรันก่อนก็ได้ แต่อ่านแนวคิดไว้:

INSERT
OLD ไม่มี
NEW มี

UPDATE
OLD มี
NEW มี

DELETE
OLD มี
NEW ไม่มี

*/


