-- 1. หายอดเงินฝากรวมทั้งหมด
SELECT SUM(balance) AS Total_Deposit
FROM deposit_accounts;

-- 2. หายอดเงินฝากเฉลี่ย
SELECT AVG(balance) AS Average_Deposit
FROM deposit_accounts;

-- 3. หายอดฝากสูงสุด
-- Version: Show only deposit amount
SELECT 
	MAX(balance) AS Maximum_deposit_amount
FROM deposit_accounts;
-- Version: Show name of member and show all deposit account
SELECT 
	m.member_id,
	m.full_name,
	MAX(d.balance) AS Maximum_deposit_amount
FROM members m
JOIN deposit_accounts d
ON m.member_id = d.member_id
GROUP BY m.member_id, m.full_name, d.balance
ORDER BY d.balance DESC;
-- Not all of deposit account
SELECT 
	m.member_id,
	m.full_name,
	d.account_no,
	d.balance
FROM members m
JOIN deposit_accounts d
ON m.member_id = d.member_id
ORDER BY d.balance DESC
LIMIT 1;
-- All of deposit account
SELECT 
	m.member_id,
	m.full_name,
	SUM(d.balance) AS Total_Deposit_Amount
FROM members m
JOIN deposit_accounts d
ON m.member_id = d.member_id
GROUP BY m.member_id, m.full_name
ORDER BY SUM(d.balance) DESC
LIMIT 1;
-- Test add deposit acc to sathit
INSERT INTO deposit_accounts
(member_id, account_no, account_type, balance, opened_date)
VALUES
(5, 'D004', 'SAVING', 50000, '2026-01-19');
SELECT * FROM deposit_accounts;


-- 4. สรุปยอดฝากแยกตาม account_type
-- V1: ลืมนึกว่าข้มูลแยกกกัน 2 Tables
SELECT
	m.member_id,
	m.full_name,
	d.member_id,
	d.account_type,
	SUM(d.balance) AS Total_Deposit_Amount
FROM members m
JOIN deposit_accounts d
ON m.member_id = d.member_id
GROUP BY m.member_id, m.full_name, d.member_id, d.account_type
/* Versoin Fix 2: นึกได้ว่าข้อมูลยอดฝาก / ประเภทบัญชีอยู่ใน deposit_accounts เดียวกันไม่จำเป้นต้อง JOIN
ลืมไปว่าจะเรียงโชว์ข้อมูลโดยยึดกลุ่มตาม Collum ผ่าน Group ยังไง*/
SELECT
	SUM(balance) AS Total_Deposit_Amount
FROM deposit_accounts
GROUP BY account_type
ORDER BY balance DESC;
-- V3: ย้อนไปทบทวนวิธีเลือกแสดงผลแบบหมวดหมู่เฉพาะ จนได้ผลลัพธ์ดังนี้
SELECT account_type, SUM(balance) AS Total_Balance_Amount
FROM deposit_accounts
GROUP BY account_type
ORDER BY Total_Balance_Amount DESC;

-- 5. แสดงชื่อสมาชิก + ยอดฝากรวมของแต่ละคน
-- SUM Version
SELECT
	m.member_id,
	m.full_name,
	d.member_id,
	d.account_type,
	SUM(d.balance) AS Total_Deposit_Memeber
FROM members m
JOIN deposit_accounts d
ON m.member_id = d.member_id
GROUP BY m.member_id, m.full_name, d.account_type, d.member_id
ORDER BY Total_Deposit_Memeber DESC;
-- Version ASk AI to fix
SELECT
	m.member_id,
	m.full_name,
	SUM(d.balance) AS Total_Deposit_Memeber
FROM members m
JOIN deposit_accounts d
ON m.member_id = d.member_id
GROUP BY m.member_id, m.full_name
ORDER BY Total_Deposit_Memeber DESC;

-- No sum version
SELECT
	m.member_id,
	m.full_name,
	d.member_id,
	d.account_type,
	d.balance
FROM members m
JOIN deposit_accounts d
ON m.member_id = d.member_id
GROUP BY m.member_id, m.full_name, d.account_type, d.member_id, d.balance
ORDER BY d.balance DESC;

-- 6. แสดงเฉพาะสมาชิกที่มียอดฝากรวม > 10000
SELECT
	m.member_id,
	m.full_name,
	SUM(d.balance) AS Total_Deposit_Amount
FROM members m
JOIN deposit_accounts d
ON m.member_id = d.member_id
GROUP BY m.member_id, m.full_name
HAVING SUM(d.balance) > 10000
ORDER BY Total_Deposit_Amount DESC;

-- 7. หาสมาชิกที่ยังไม่มีบัญชีเงินฝาก
-- ทำไม่ได้ จำหรือไม่รู้คำสั่งใช้เช็คจำนวนค่า
-- Version fix by AI
SELECT
    m.member_id,
    m.member_no,
    m.full_name
FROM members m
LEFT JOIN deposit_accounts d
ON m.member_id = d.member_id
WHERE d.account_id IS NULL
ORDER BY m.member_id;
/*WHERE d.balance IS NULL
AND d.balance = 0
AND d.balance IS NULL
HAVING d.balance < 1
ORDER BY SUM(d.balance) DESC;*/

-- 8. สร้าง loans
CREATE TABLE loans (
    loan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL REFERENCES members(member_id),
    loan_no VARCHAR(30) UNIQUE NOT NULL,
    loan_type VARCHAR(30) NOT NULL,
    principal NUMERIC(14,2) NOT NULL CHECK (principal > 0),
    annual_rate NUMERIC(5,2) NOT NULL CHECK (annual_rate >= 0),
    start_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);
-- Fix Add Check in column data
/*ALTER TABLE loans
ADD CONSTRAINT chk_loans_principal_positive
CHECK (principal > 0);
ALTER TABLE loans
ADD CONSTRAINT chk_loans_anual_rate_positive
CHECK (principal > 0);*/

-- 9. เพิ่มเงินกู้ 2 รายการ
INSERT INTO loans
(member_id, loan_no, loan_type, prancipal, annual_rate, start_date)
VALUES
(2, 'L001', 'ORDINARY', 150000.00, 5.50, '2025-05-15'),
(3, 'L002', 'ORDINARY', 50000.00, 6.00, '2025-05-15'),
(5, 'L003', 'ORDINARY', 80000.00, 3.00, '2025-05-15');
SELECT * FROM loans;

-- 10. JOIN members กับ loans แล้วแสดง
-- member_no, full_name, loan_no, loan_type, principal
SELECT 
	m.member_id,
	m.member_no,
	m.full_name,
	l.loan_id,
	l.loan_no,
	l.loan_type,
	l.principal
FROM members m
JOIN loans l
ON m.member_id = l.member_id

-- Fix name in column
ALTER TABLE loans
RENAME COLUMN prancipal TO principal;
-- Read table
SELECT * FROM loans;




