/*
แบบฝึกหัด Exercise 4
1. CREATE TABLE audit_logs
2. CREATE FUNCTION audit_loans_changes()
3. CREATE TRIGGER trg_audit_loans_update
4. UPDATE loan_id = 7
5. SELECT ดู audit_logs
6. ดึง old principal / new principal จาก JSONB
7. ลอง UPDATE loan เดิมอีกครั้ง
8. เช็กว่ามี Audit Log เพิ่มอีก 1 แถว

โบนัส:
9. เพิ่มคอลัมน์ changed_by
10. ใส่ค่า 'admin_test' ลง log

เช่น:
ALTER TABLE audit_logs
ADD COLUMN changed_by VARCHAR(100);

หลักจำวันนี้
Trigger
= เหตุการณ์เกิดแล้ว DB ทำงานอัตโนมัติ

OLD
= ก่อนแก้

NEW
= หลังแก้

Audit Log
= ประวัติว่าใครทำอะไรกับข้อมูลเมื่อไร

JSONB
= เก็บข้อมูลแบบ JSON ที่ query ต่อได้

AFTER UPDATE
= ทำงานหลัง UPDATE สำเร็จ

ในระบบการเงิน Audit Log สำคัญมาก เพราะถ้ามีคนแก้ยอดเงิน เราต้องตรวจย้อนหลังได้ว่า ก่อนแก้เท่าไร หลังแก้เท่าไร และแก้เมื่อไร
ทำข้อ 1–8 ก่อน แล้วส่ง SQL มา เดี๋ยวผมตรวจให้ทีละบรรทัด จากนั้นค่อยต่อ Trigger INSERT/UPDATE/DELETE 
แบบ Function เดียว + changed_by + audit trail ที่สมบูรณ์ขึ้น ครับ

*/

-- 1. CREATE TABLE audit_logs
-- Delete Old Table
DROP TABLE audit_logs;
-- Delete Trigger & Function
-- 1. ลบ Trigger ที่ตาราง loans ออกก่อน
DROP TRIGGER IF EXISTS trg_audit_loans_update ON loans;
-- 2. เมื่อไม่มีใครเรียกใช้แล้ว จึงจะลบฟังก์ชันได้สำเร็จ
DROP FUNCTION IF EXISTS audit_loans_changes();
-- Create Data
CREATE TABLE audit_logs(
	audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Log Key / ID

	table_name VARCHAR(50) NOT NULL, -- table log name
	record_id INTEGER NOT NULL, -- ID of record has edit

	record_type VARCHAR(30) NOT NULL, -- INSERT / UPDATE / DELETE

	old_data JSONB, -- old data in json style
	new_data JSONB,-- new data in json style

	changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- Edit time
);


-- 2. CREATE FUNCTION audit_loans_changes()
CREATE OR REPLACE FUNCTION audit_loans_changes()
RETURNS TRIGGER
AS $$
BEGIN
	INSERT INTO audit_logs
	(
		table_name,
		record_id,
		record_type,
		old_data,
		new_data,
		changed_by
	)
	VALUES
	(
		'loans',
		NEW.loan_id,
		'UPDATE',
		to_jsonb(OLD),
		to_jsonb(NEW),
		 current_user
	);
	
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. CREATE TRIGGER trg_audit_loans_update
CREATE TRIGGER trg_audit_loans_update
AFTER UPDATE
ON loans
FOR EACH ROW
EXECUTE FUNCTION audit_loans_changes();


-- View data in loans
SELECT * FROM loans;
-- 4. UPDATE loan_id = 7
UPDATE loans
SET annual_rate = 5.00
WHERE loan_id = 7;


-- 5. SELECT ดู audit_logs
SELECT * FROM audit_logs;



-- 6. ดึง old principal / new principal จาก JSONB
SELECT 
	
		audit_id,
		old_data ->> 'annual_rate' AS old_rate,
		new_data ->> 'annual_rate' AS new_rate,
		changed_at
	
FROM audit_logs
ORDER BY audit_id DESC;


-- 7. ลอง UPDATE loan เดิมอีกครั้ง
UPDATE loans
SET annual_rate = 10.00
WHERE loan_id = 8;

-- 8. เช็กว่ามี Audit Log เพิ่มอีก 1 แถว
SELECT 
	audit_id,
	old_data ->> 'annual_rate' AS old_rate,
	new_data ->> 'annual_rate' AS new_rate,
	changed_at
FROM audit_logs
ORDER BY audit_id;

/*โบนัส:*/
--9. เพิ่มคอลัมน์ changed_by
ALTER TABLE audit_logs
ADD COLUMN changed_by VARCHAR(100);
SELECT * FROM audit_logs;


--10. ใส่ค่า 'admin_test' ลง log
UPDATE audit_logs
SET changed_by = 'admin_test'
WHERE audit_id = 6;
-- กรณีใส่ทุกจุดที่ changed_by IS NULL,
UPDATE audit_logs
SET changed_by = 'admin_test'
WHERE changed_by IS NULL;

/*เช่น:
ALTER TABLE audit_logs
ADD COLUMN changed_by VARCHAR(100);*/



-- TEST CREAET FUNCTION
CREATE OR REPLACE FUNCTION test_function()
RETURNS TRIGGER
AS $$
BEGIN

	INSERT INTO audit_logs
	(
		table_name,
		record_id,
		record_type,
		old_data,
		new_data,
		changed_by
	)
	VALUES
	(
		'loans',
		NEW.loan_id,
		'UPDATE',
		to_jsonb(OLD),
		to_jsonb(NEW),
		current_user
	);

RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger
CREATE OR REPLACE TRIGGER test_trigger
AFTER UPDATE
ON loans
FOR EACH ROW
EXECUTE FUNCTION test_function();

-- Update loans data
UPDATE loans
SET status = 'TEST'
WHERE loan_id = 7;

SELECT * FROM audit_logs;


-- 7. ตัวใหม่ที่ต้องเรียน: TG_OP
CREATE OR REPLACE FUNCTION audit_loans_changes()
RETURNS TRIGGER
AS $$
BEGIN

	IF TG_OP = 'INSERT' THEN

	INSERT INTO audit_logs
	(
		table_name,
		record_id,
		record_type,
		old_data,
		new_data,
		changed_by
	)
	VALUES
	(
		TG_TABLE_NAME,
		NEW.loan_id,
		TG_OP,
		 NULL,
		to_jsonb(NEW),
		current_user
	);

	RETURN NEW;
	
	ELSIF TG_OP = 'UPDATE' THEN

	INSERT INTO audit_logs
	(
		table_name,
		record_id,
		record_type,
		old_data,
		new_data,
		changed_by
	)
	VALUES
	(
		TG_TABLE_NAME,
		NEW.loan_id,
		TG_OP,
		to_jsonb(OLD),
		to_jsonb(NEW),
		current_user
	);

	RETURN NEW;
	
	ELSIF TG_OP = 'DELETE' THEN

	INSERT INTO audit_logs
	(
		table_name,
		record_id,
		record_type,
		old_data,
		new_data,
		changed_by
	)
	VALUES
	(
		TG_TABLE_NAME,
		OLD.loan_id,
		TG_OP,
		to_jsonb(OLD),
		 NULL,
		current_user
	);

	RETURN OLD;
	END IF;

END;
$$ LANGUAGE	plpgsql;

-- Connect TRIGGER to Function
CREATE OR REPLACE TRIGGER trg_audit_loan_change
AFTER INSERT OR UPDATE OR DELETE
ON loans
FOR EACH ROW
EXECUTE FUNCTION audit_loans_changes();

-- Test 1 — INSERT
INSERT INTO loans
(
 member_id,
 loan_no,
 loan_type,
 principal,
 annual_rate,
 start_date
)
VALUES
(
	2,
	'L_TEST_001',
    'TEST',
    10000.00,
    5.00,
    CURRENT_DATE
);

-- Test 2 — UPDATE
UPDATE loans
SET annual_rate = 10.00
WHERE loan_no = 'L_TEST_001';

-- Test 3 — DELETE
DELETE FROM loans
WHERE loan_no = 'L_TEST_001';

-- VIEW audit_logs
SELECT *
FROM audit_logs
ORDER BY audit_id DESC;

-- Clear all data in table
TRUNCATE TABLE audit_logs RESTART IDENTITY;

-- ลอง Query ให้เห็นง่ายขึ้น
SELECT
	audit_id,
	table_name,
	record_id,
	record_type,
	old_data ->> 'loan_no' AS old_loan_no,
	new_data ->> 'loan_no' AS new_loan_no,
	old_data ->> 'annual_rate' AS old_rate,
	new_data ->> 'annual_rate' AS new_rate,
	changed_at,
	changed_by
FROM audit_logs
ORDER BY audit_id DESC;

/*หลักจำ TG_OP ทั้งหมด

ให้เขียนไว้ท้าย Exercise 4 แบบนี้ได้เลย:*/
/*TG_OP
= INSERT / UPDATE / DELETE ที่เรียก Trigger

TG_TABLE_NAME
= ชื่อตารางที่ Trigger กำลังทำงาน

INSERT
OLD ❌
NEW ✅
RETURN NEW

UPDATE
OLD ✅
NEW ✅
RETURN NEW

DELETE
OLD ✅
NEW ❌
RETURN OLD

IF
ELSIF
ELSIF
END IF*/

-- TEST CREAT FUNCTION TG_OP
CREATE OR REPLACE FUNCTION test_crate_function_01()
RETURNS TRIGGER
AS $$
BEGIN

	IF TG_OP = 'INSERT' THEN

	RETURN NEW;

	ELSIF TG_OP = 'UPDATE' THEN

	RETURN NEW;

	ELSIF TG_OP = 'DELETE' THEN

	RETURN OLD;

	END IF;
END;
$$ LANGUAGE plpgsql;

-- CHECK trigger
SELECT
	trigger_name,
	event_manipulation,
	event_object_table
FROM information_schema.triggers
WHERE event_object_table = 'loans';

